version: '2.1'

networks:
  db:
    driver: bridge
    internal: true

services:
  hsqldb:
    build: ./database/
    image: yatharthranjan89/hsqldb
    restart: always
    networks:
      - db
    ports:
      - 9001:9001
    volumes:
      - ../../xmpp-db:/usr/hsql/
      - ./database/server.properties:/etc/opt/hsqldb/conf/server.properties
      - ./database/sqltool.rc:/etc/opt/hsqldb/conf/sqltool.rc

  xmppserver:
    build: ../
    image: radarbase/xmppserver:dev
    restart: always
    networks:
      - default
      - db
    depends_on:
      - hsqldb
    environment:
      RADAR_XMPP_FCM_SENDER_KEY: "1043784930865"
      RADAR_XMPP_FCM_SERVER_KEY: "AAAA8wZuFjE:APA91bHmsDE1mhi1aQrmcTNT--RAofoVdcgc6wkCS1BTeHui4mdwOhaeum_D4dMcaQ4pfe9vuwJWZFWOF9EJ-JN8mkzMZ2Crm7LGK1WD2NMA-xd3xIkoNQx8jU0dySAzhbzWyI5LB9ljvliUgXWVFaj3-uQSZfzfdA"
      RADAR_XMPP_SCHEDULER_TYPE: "server"
      RADAR_XMPP_DB_PATH: "//hsqldb:9001/notification"
      RADAR_XMPP_CACHE_EXPIRY: 300
      JAVA_OPTS: "-Xms2G -Xmx10G"

#    volumes:
#      - ../../xmpp-db:/usr/hsql/
